---
- name: Deploy App to EC2
  hosts: app
  become: yes
  vars:
    repo_name: myapp
    aws_region: ap-south-1
    aws_account_id: 506115906214
    repo_url: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ repo_name }}"
  tasks:
    - name: Install Docker
      amazon.aws.ec2_metadata_facts: {}
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Authenticate Docker with ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ repo_url }}

    - name: Pull Docker Image from ECR
      shell: docker pull {{ repo_url }}

    - name: Stop old container if running
      shell: |
        docker stop my-app || true
        docker rm my-app || true

    - name: Run new container
      shell: |
        docker run -d --name my-app -p 5000:5000 {{ repo_url }}
