- name: Install Docker, Jenkins and dependencies on CICD server
  hosts: cicd
  become: true

  tasks:
    - name: Install dependencies
      yum:
        name:
          - docker
          - python3
          - python3-pip
          - ansible
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install pip packages
      pip:
        name:
          - boto3
          - botocore

    - name: Pull Jenkins Docker image
      shell: docker pull jenkins/jenkins:lts


    - name: Remove existing Jenkins container (if it exists)
      shell: |
        docker rm -f jenkins || true


    - name: Run Jenkins container
      shell: |
        docker run -d \
        --name jenkins \
        -p 8080:8080 \
        -p 50000:50000 \
        -v /var/jenkins_home:/var/jenkins_home \
        -v /var/run/docker.sock:/var/run/docker.sock \
        jenkins/jenkins:lts

     # Updated Task: Wait for Jenkins to Initialize
    - name: Wait for Jenkins to become available
      uri:
        url: http://localhost:8080/login
        status_code: 200
        validate_certs: no
      register: jenkins_health_check
      retries: 60
      delay: 5
      until: jenkins_health_check.status == 200


    - name: Get Jenkins initial admin password
      shell: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_password
      failed_when: jenkins_password.stdout == ""


    - name: Display Jenkins login information
      debug:
        msg: |
          Jenkins is now running at http://{{ ansible_host }}:8080
          {% if jenkins_password.stdout %}
          Temporary Admin Password: {{ jenkins_password.stdout }}
          {% else %}
          Unable to retrieve the temporary admin password. Please check the Jenkins container logs.
          {% endif %}
